services:
  # servidor web
  lucee:
    container_name: lucee-docker
    build:
      context: .
    ports:
      - '8888:8888'
    volumes:
      - ./webroot:/var/www
    networks:
      - lucee-network
    environment:
      - LUCEE_ADMIN_PASSWORD=@Lucee2025!

networks:
  lucee-network:
    driver: bridge
