version: '3.8'

services:
  # servidor web
  lucee:
    container_name: lucee-docker
    build:
      context: ./lucee
    ports:
      - '8888:8888'
    volumes:
      - ./webroot:/lucee/webapps/ROOT
    networks:
      - lucee-network

networks:
  lucee-network:
    driver: bridge